[features]
seeds = false
skip-lint = false
[programs.devnet]
# value_router = "EajzKnjgqctLn1LgqeCMUscTT7g2QiEex63hCH7HBzot"
# value_router = "97jJVm6gLtNFa6r2ocKrp8WbF7SzKvtHjWPMFhvVEo1p"
value_router = "Gu2frGkJbf8WAxwsv7zFQ7r5wwZo4hdoKrYNE72waXyV"


[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
#cluster = "http://127.0.0.1:8899"
#cluster = "https://api.mainnet-beta.solana.com"
#cluster = "https://api.testnet.solana.com"
#cluster = "https://devnet.helius-rpc.com/?api-key=34591cc1-fd65-44d3-a283-1dbd8970e594"
cluster = "https://mainnet.helius-rpc.com/?api-key=34591cc1-fd65-44d3-a283-1dbd8970e594"
wallet = "/home/justin/solflare/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
