[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
value_router = "4i7opQGfdy5LTBA26qq8HF7mTKtve5jBSsgmF6UP2fbm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://blue-omniscient-friday.solana-mainnet.quiknode.pro/59ccc9be093f05d398a9256ef883d0b9ad4857e2"
wallet = "/home/justin/solflare/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
